CREATE TABLE IF NOT EXISTS memo (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'メモID',
title VARCHAR(80) NOT NULL PRIMARY KEY COMMENT 'タイトル',
content VARCHAR(512) NOT NULL PRIMARY KEY COMMENT 'コンテンツ',
deleted BOOLEAN NOT NULL DEFAULT FALSE COMMENT '削除フラグ',
created_at TIMESTAMP DEFAULT current_timestamp COMMENT '作成日',
updated_at TIMESTAMP DEFAULT current_timestamp ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日'
) COMMENT='メモ';
